[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
shaayud_core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
sqlx = { version = "0.8", features = [
    "postgres",
    "runtime-tokio-rustls",
    "macros",
] }
tracing = "0.1"
tracing-subscriber = "0.3"
hyper = "1.6"
anyhow = "1.0"

neo4rs = "0.8"
